'use client';
// import type { Metadata } from "next";
import "./globals.css";
import Head from 'next/head'
import { GradientProvider } from "@/components/general/GradientContextWidget";
import { CursorProviderWidget } from "@/components/general";



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!overflow-x-hidden">
      <Head>
        <meta name="theme-color" content="#000000" />
      </Head>
      <body
        className={` antialiased bg-black`}
      >
        <CursorProviderWidget />
        <GradientProvider>
            {children}
        </GradientProvider>
      </body>
    </html >
  );
}
